"""Add User ID FK to graph model

Revision ID: cdb24a66246d
Revises: b7c1d2e3f4a5
Create Date: 2026-08-29 13:16:20.608775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb24a66246d'
down_revision: Union[str, Sequence[str], None] = 'b7c1d2e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphs', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_graphs_user_id'), 'graphs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'graphs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'graphs', type_='foreignkey')
    op.drop_index(op.f('ix_graphs_user_id'), table_name='graphs')
    op.drop_column('graphs', 'user_id')
    # ### end Alembic commands ###
